name: Deploy Portfolio to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Важно явно указать версию Node, чтобы сборка была предсказуемой
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # ci работает быстрее и надежнее чем install для CI/CD

      - name: Build project
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Создаем папку на сервере, если её нет (чтобы scp не ругался)
      - name: Create folder on server
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /root/portfolio"

      # Чистим старые файлы перед заливкой (опционально, но полезно)
      - name: Clean old files
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -rf /root/portfolio/*"

      # Копируем новые файлы
      - name: Deploy Files
        run: |
          scp -r out/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/root/portfolio/